// use client를 작성해야 client component로 인식함 그렇지 않으면 next.js는 server component로 인식함
// "use client";
import "./globals.css";
import Link from "next/link";

// metadata 설정 부분
export const metadata = {
  title: "Web tutorials",
  description: "Generated by sunghyuk",
};

export default async function RootLayout({ children }) {
  const resp = await fetch("http://localhost:9999/topics");
  const topics = await resp.json();

  // 기존 client 방식
  // useEffect(() => {
  //   refreshList();
  // }, []);

  // const refreshList = () => {
  //   fetch("http://localhost:9999/topics")
  //     .then((res) => {
  //       return res.json();
  //     })
  //     .then((result) => {
  //       setList(result);
  //     })
  //     .catch((e) => {
  //       console.log(e);
  //     });
  // };

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((item) => {
            return (
              <li key={item.id}>
                <Link href={`/read/${item.id}`}>{item.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <img src="/vercel.svg" alt="vercel image" />
        <ul>
          <li>
            <Link href="/create">Create</Link>
          </li>
          <li>
            <Link href="update/1">Update</Link>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ul>
      </body>
    </html>
  );
}
